# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/jlinc-did-client

    docker:
      - image: circleci/node:8.9.4

    steps:
      - checkout
      - run: git submodule update --init
      - run: wget -qO- https://binaries.cockroachdb.com/cockroach-v2.1.2.linux-amd64.tgz | tar  xvz
      - run: sudo cp -i cockroach-v2.1.2.linux-amd64/cockroach /usr/local/bin
      - run:
          name: start cockroach
          command: cockroach start --insecure --listen-addr=localhost
          background: true

      # Download and cache dependencies
      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - node_modugstles-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "package.json" }}

      # run tests!
      - run: npm test
