# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/jlinc-did-client

    docker:
      - image: circleci/node:8.11.3
        environment:
        - DATABASE_HOST: postgresql://root@127.0.0.1
        - PGHOST: 127.0.0.1
        - PGUSER: root
      - image: circleci/postgres:9.6-alpine
        environment:
        - POSTGRES_USER: root
    steps:
      - run: sudo apt-get clean
      - run: sudo apt-get update
      - run: sudo apt-get install -y postgresql-client

      - checkout
      - run: git submodule update --init

      # Download and cache dependencies
      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - node_modugstles-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "package.json" }}

      # run tests!
      - run: npm test
